优化Execute
Lazuplis-Mei/pvzclass pull request #90
Opened 2023-11-20 05:06 UTC by Moon-404

使用内存Hook的方式，在游戏每次update更新之前统一执行Execute代码，详细更新内容如下：
1. 将所有CT表移到CT文件夹中，方便后人查阅。
2. Memory类新增：immediateExecute，用于控制是否立即执行Execute代码，否则等待PVZ更新前再执行；WaitPVZ，用于等待PVZ运行至更新前；ResumePVZ，用于让阻塞的PVZ再次运行。
3. InitPVZ时将Execute的Hook代码注入，占用Variable的0x500-0x600空间。
4. 优化Variable的注释。
5. pvzclass示例中，如果注释20、21、29行，则每一次更新只创建一个僵尸；如果不注释，可以让一次更新执行多次Execute。

2023-11-20 08:52 UTC, Violet-Nonbloosom requested changes

2023-11-20 08:52 UTC, Violet-Nonbloosom commented on pvzclass/PVZ.cpp
> +		Memory::WriteArray<BYTE>(0x415920, STRING(__asm__UpdateHook));
这段代码应该注入到 `0x415920` 么？
据我所知，自带的函数中就有1/4 不需要 `Board` 存在就能运行。

2023-11-21 05:20 UTC, Moon-404 commented on pvzclass/PVZ.cpp
> +		Memory::WriteArray<BYTE>(0x415920, STRING(__asm__UpdateHook));
我是觉得这个注入点比较合适，如果你有更好的注入点推荐跟我说就是了，我去改一下也不麻烦。
此外，这个优化是为了解决Execute在关卡中随机出现的AccessViolation问题，在关卡外需要调用的Execute也不多，这样反而是一种避免关卡外调用关卡内函数的保险。而且在不需要这个功能的时候，可以通过设置immediateExecute来禁用它，也足够灵活。

2023-11-21 07:24 UTC, Violet-Nonbloosom commented on pvzclass/PVZ.cpp
> +		Memory::WriteArray<BYTE>(0x415920, STRING(__asm__UpdateHook));
这个优化有一个问题：游戏暂停时 `0x415920` 不会被调用。

这意味着所有 `Execute()` 都会被游戏暂停阻断。对于修改器类程序，这可能造成修改者误判修改器使用情况，造成意外后果。

至于新的注入点，可以试试 `0x415D40` 或者 `0x416064`。

2023-11-22 01:44 UTC, Moon-404 commented on pvzclass/PVZ.cpp
> +		Memory::WriteArray<BYTE>(0x415920, STRING(__asm__UpdateHook));
已将注入地点更改至415D40

2023-11-22 06:16 UTC, merged